version: '3.4'

name: aichemy
services:
  xttsapiserver:
    image: xttsapiserver
    container_name: aichemy-xtts-server
    env_file: .env
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-8020}:${CONTAINER_PORT:-8020}"
    volumes:
      - ./xtts-server:/xtts-server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    networks:
      xtts-aichemy-network:
        aliases:
          - xtts-server
networks:
  xtts-aichemy-network:
    external: true
